### PR TITLE
Add Intelecy logo

### PR DESCRIPTION
**Pull request by kung-foo**
A bit hard to preview since the target image will endup in the main branch. Not sure how to properly scale things since all the logos have different aspect ratios.

Preview light:
Screenshot 2021-10-25 at 14-13-51 opcua README md at add-logo · gopcua opcua

---

Preview dark:
Screenshot 2021-10-25 at 14-13-17 opcua README md at add-logo · gopcua opcua

### CODE REVIEW

**Comment by magiconair** [comment]
Need to see how we can either invert the NV logo or use a different one for dark mode. Probably just one with a white background

**Comment by magiconair** [comment]
updated both nv and evosoft logo to use white backgrounds.

**Comment by magiconair** [comment]
I leave it up to you if you want to do the same for intelecy.

**Comment by kung-foo** [comment]
logo updated

**Pull request merged**
