### PR TITLE
Fix secure channel races (attempt 1)

### PR DESCRIPTION
**Pull request by magiconair**
This is the first attempt to address the data races in the secure channel. I am not fully comfortable with the code yet since I don't fully understand it yet. 

What I've concluded so far is that the `reset()` method is the main reason for the data races since it does a lot more than just resetting the `closing` and `disconnected` channels. It also resets other data structures which are guarded by other locks like the `instances`, `chunks` and the `handlers`. 

`reset()` is only called when the secure channel is closed and since the client implementation never re-uses an existing secure channel instance I don't think this method is required at all. 

Removing `reset()` immediately fixed all the data races we got with `make test-race` but generated a `panic: send on closed channel`.  This is because outstanding requests try to bubble up errors to the client via the `sechanErr` channel which the client closes in its `Close()` method. Since we are closing the client it seems OK to leave the `sechanErr` channel open to avoid this panic. However, we should try to shutdown all outstanding requests properly in the secure channel before returning. So I consider not closing the `sechanErr` a bit of a hack. 

Update: I think I've found the culprit for the `panic` and fixed it. 

See #376
See #460 
See #459

### CODE REVIEW

**Comment by magiconair** [comment]
@kung-foo and @antlad it would be great if you could test this change in your setups. 

I will try to understand the secure channel code better. There are a lot of locks in this code and I'll check if we need them all.

**Comment by antlad** [comment]
@magiconair I tried 9b0f3af7862b commit on auto tests. Tests passing, but issue #460 still present.

**Comment by magiconair** [comment]
Ok thank you. I'll keep digging

**Comment by magiconair** [comment]
@antlad 9b0f3af does not contain the full changeset. Could you try a9f3ac5 instead? The CI flow found another data race which I'm looking at but this seems to be in a different spot.

**Comment by magiconair** [comment]
@antlad could you also post a new stacktrace so that I can get the correct line numbers?

**Comment by magiconair** [comment]
Well, after looking at the code a bit more I realize that most of the locks have been there before 😊 It just has been a while since I've looked at it.

**Comment by antlad** [comment]
@magiconair Sorry, looks like missed this commit a9f3ac5 . Just checked CI, looks much better. No data races detected.

**Comment by magiconair** [comment]
Yay. Thank you

**Comment by magiconair** [comment]
Still getting a race:
```
==================
WARNING: DATA RACE
Write at 0x00c000068850 by goroutine 49:
  runtime.recvDirect()
      /Users/frank/sdk/go1.17.1/src/runtime/chan.go:346 +0x7c
  github.com/gopcua/opcua.(*Client).Close()
      /Users/frank/src/github.com/gopcua/opcua/client.go:517 +0x104
  github.com/gopcua/opcua/uatest.TestAutoReconnection()
      /Users/frank/src/github.com/gopcua/opcua/uatest/reconnection_test.go:154 +0x1400
  testing.tRunner()
      /Users/frank/sdk/go1.17.1/src/testing/testing.go:1259 +0x198

Previous read at 0x00c000068850 by goroutine 75:
  runtime.chansend1()
      /Users/frank/sdk/go1.17.1/src/runtime/chan.go:144 +0x3c
  github.com/gopcua/opcua/uasc.(*SecureChannel).dispatcher()
      /Users/frank/src/github.com/gopcua/opcua/uasc/secure_channel.go:192 +0x1ec

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/frank/sdk/go1.17.1/src/testing/testing.go:1306 +0x5b8
  testing.runTests.func1()
      /Users/frank/sdk/go1.17.1/src/testing/testing.go:1598 +0xac
  testing.tRunner()
      /Users/frank/sdk/go1.17.1/src/testing/testing.go:1259 +0x198
  testing.runTests()
      /Users/frank/sdk/go1.17.1/src/testing/testing.go:1596 +0x780
  testing.(*M).Run()
      /Users/frank/sdk/go1.17.1/src/testing/testing.go:1504 +0x928
  main.main()
      _testmain.go:49 +0x288

Goroutine 75 (finished) created at:
  github.com/gopcua/opcua/uasc.(*SecureChannel).open.func1()
      /Users/frank/src/github.com/gopcua/opcua/uasc/secure_channel.go:481 +0x4c
  sync.(*Once).doSlow()
      /Users/frank/sdk/go1.17.1/src/sync/once.go:68 +0xb8
  sync.(*Once).Do()
      /Users/frank/sdk/go1.17.1/src/sync/once.go:59 +0x50
  github.com/gopcua/opcua/uasc.(*SecureChannel).open()
      /Users/frank/src/github.com/gopcua/opcua/uasc/secure_channel.go:480 +0x10c
  github.com/gopcua/opcua/uasc.(*SecureChannel).Open()
      /Users/frank/src/github.com/gopcua/opcua/uasc/secure_channel.go:460 +0x27c
  github.com/gopcua/opcua.(*Client).Dial()
      /Users/frank/src/github.com/gopcua/opcua/client.go:498 +0x24c
  github.com/gopcua/opcua.(*Client).monitor()
      /Users/frank/src/github.com/gopcua/opcua/client.go:330 +0x1014
==================
=== CONT  TestAutoReconnection
    testing.go:1152: race detected during execution of test
--- FAIL: TestAutoReconnection (3.68s)
    --- PASS: TestAutoReconnection/connection_failure (0.21s)
    --- PASS: TestAutoReconnection/securechannel_failure (0.83s)
    --- PASS: TestAutoReconnection/session_failure (1.05s)
    --- PASS: TestAutoReconnection/subscription_failure (0.94s)
```

**Comment by magiconair** [comment]
Still one test failing on go1.16-32bit

```
=== RUN   TestAutoReconnection/connection_failure
Unknown message received FourByteNodeId(i=841)
    reconnection_test.go:130: Timeout reached, the connection did not go down as expected
--- FAIL: TestAutoReconnection (7.02s)
    --- FAIL: TestAutoReconnection/connection_failure (5.10s)
```

**Comment by kung-foo** [comment]
Sorry I haven't been able to really test this. When I make a race build, it breaks some bit of the Windows Service Manager lib (which we use) and I haven't had time to track down _that_ (for ref: https://github.com/golang/go/issues/38355).

**Comment by magiconair** [comment]
I've dropped support for circleci and rebased the branch to `main`.

**Comment by magiconair** [comment]
I'll merge this and then we will start to test this on our systems.

**Pull request merged**
