### PR TITLE
add variant array limit

### PR DESCRIPTION
**Pull request by kung-foo**
fix for #248

### CODE REVIEW

**Review by magiconair — COMMENTED** [review]
1. Could you please rebase the change to master so that the v0.1.4 fix is in. 
1. I think it'd be better to handle the error for the big array as a special test case instead of extending the `CodecTest` this way. 
1. Could you try to find a status code that expresses the error instead of the custom error?

Thx

**Comment by kung-foo** [comment]
lol. if you force push (to first remove a merge commit) and it results in an "empty" PR, it seems like github automatically "merges" and closes it. :man_shrugging: will re-create.

**Comment by kung-foo** [comment]
rebased and test code moved into own func

Regarding the error code, as a user, I want to be able to quickly figure out why I got the error. I could return something like `io.ErrShortBuffer`, but that isn't exactly right because it's not that the buffer is too small, it's that we (arbitrarily) added a safety limit. IMO, errors should clearly explain what is going on, and what the user needs to do to fix it.

**Comment by magiconair** [comment]
So far we've been trying to stick to the available `StatusCode`s for consistency and I'm wondering whether we can use one of them. There is `StatusBadEncodingLimitsExceeded` which seems close but I also get your point. Question is how often that's going to happen to justify an exception for not using a status code. 

Could you have a quick look how FreeOPCUA and open62541 are handling this?

**Comment by magiconair** [comment]
Maybe also squash the commits since now your change to `CodecTest` and the reverse is in. Unless I'm missing something.

**Comment by kung-foo** [comment]
ahh, I see your point re the `StatusCode`. I wasn't familiar with that code. I'll change and squash.

**Pull request merged**
