### PR TITLE
guard against double close

### LINKED ISSUE #430: panic: close of closed channel
I'm using multiple subscriptions under one client. In order to stop my code, I first cancel all the subscriptions using `Subscription.Cancel()`, then I do `Client.Close()`. I get following error,

```
panic: close of closed channel

goroutine 16 [running]:
github.com/gopcua/opcua/uasc.(*SecureChannel).Close.func1(0xc0035800e0)
        /home/salman/go/pkg/mod/github.com/gopcua/opcua@v0.2.0-rc2/uasc/secure_channel.go:838 +0x2f
github.com/gopcua/opcua/uasc.(*SecureChannel).Close(0xc0035800e0, 0xa95d00, 0xc0001120d0)
        /home/salman/go/pkg/mod/github.com/gopcua/opcua@v0.2.0-rc2/uasc/secure_channel.go:847 +0x1a5
github.com/gopcua/opcua.(*Client).monitor(0xc000bfc2a0, 0xa9ff40, 0xc002e25e00)
        /home/salman/go/pkg/mod/github.com/gopcua/opcua@v0.2.0-rc2/client.go:322 +0xfe6
created by github.com/gopcua/opcua.(*Client).Connect.func1
        /home/salman/go/pkg/mod/github.com/gopcua/opcua@v0.2.0-rc2/client.go:212 +0x65
```

### PR DESCRIPTION
**Pull request by magiconair**
This patch guards the Close() method of the secure channel to be called
more than once. This seems like a workaround I would like to remove once
we understand the root cause of the problem.

Fixes #430

### CODE REVIEW

**Comment by siscia** [comment]
This is helping a lot!

**Comment by siscia** [comment]
From this branch, I got this:

```
10:52:29.734453 error: opcua: invalid extension object with id $someid
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbf4e59]
goroutine 887 [running]:
github.com/gopcua/opcua/uacp.(*Conn).Close(0x0)
github.com/gopcua/opcua@v0.2.0-rc3.0.20210925063356-57c1a207e9d6/uacp/conn.go:207 +0x19
github.com/gopcua/opcua.(*Client).Close(0xc0013f2dd0)
github.com/gopcua/opcua@v0.2.0-rc3.0.20210925063356-57c1a207e9d6/client.go:506 +0x7d

```

**Comment by magiconair** [comment]
Looking

**Comment by magiconair** [comment]
image
Will fix...

**Comment by magiconair** [comment]
@siscia can you test with this patch, please?

**Pull request merged**
