### PR TITLE
Make TCP buffers configurable

### PR DESCRIPTION
**Pull request by magiconair**
This patch adds methods to configure the receive and transmit
buffers of the underlying TCP connection.

### CODE REVIEW

**Comment by magiconair** [comment]
We ran into this today and hard-coded the changes. Need to see whether this approach works as well or whether we need to call `SetReadBuffer/SetWriteBuffer` after `Dial` but before the `uacp` handshake for this to work.

**Comment by kung-foo** [comment]
I wonder if we should just promote the underlying conn:

```
type Conn struct {
        net.Conn
	id  uint32
	ack *Acknowledge
}
```

or if we can assume it is _always_ `TCP`:

```
type Conn struct {
        net.TCPConn
	id  uint32
	ack *Acknowledge
}
```

**Comment by magiconair** [comment]
`net.Conn` does not have the `SetRead/WriteBuffer` methods. We would have to type check twice. 

Unless we support Websockets it will be TCP and even then.

**Comment by kung-foo** [comment]
Maybe this? https://github.com/gopcua/opcua/commit/6f756f38adbbba8904af8f0b7df0d1950a7799c5

**Comment by magiconair** [comment]
This looks good. Let me test that.

**Comment by kung-foo** [comment]
note: I didn't understand this bit right here: https://github.com/gopcua/opcua/commit/6f756f38adbbba8904af8f0b7df0d1950a7799c5#diff-e06a25cad06b1ecd848e968ae7d9984eL293-R270

There's some bad naming, and aliasing going on. And I don't think there's anything that tests that path.

**Comment by magiconair** [comment]
This is for the reverse handshake but we don't have any tests for that I think.

**Pull request merged**
