### PR TITLE
enable race detection

### LINKED ISSUE #376: Data race in secure channel
Valid for 0.1.11 and 0.1.12 (didn't tried older). 
Tested with server https://github.com/Azure-Samples/iot-edge-opc-plc . 
Easy way to run `docker run --rm --network=host --mount type=bind,source="$(pwd)"/pki,target=/appdata/pki mcr.microsoft.com/iotedge/opc-plc:latest` . It will mount pki folder to local, so you can your certs on first connect from rejected to trusted. 
Looks like it happen on session timeout. Initially everything is working. Then I see this stacktrace (with -race flag). 
Next I see line `invalid response: got <nil> want **ua.PublishResponse` in `Monitor` `SetErrorHandler`.
And then no reconnection attempts and no new monitor data callbacks.

```bash
WARNING: DATA RACE
Write at 0x00c0003042e8 by goroutine 28:
  xxx/vendor/github.com/gopcua/opcua/uasc.(*SecureChannel).openSecureChannel()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:701 +0x157
  xxx/vendor/github.com/gopcua/opcua/uasc.(*SecureChannel).Renew-fm()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:660 +0x49
  xxx/vendor/github.com/gopcua/opcua.(*Client).openSecureChannel()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:193 +0x38
  xxx/vendor/github.com/gopcua/opcua.(*Client).scheduleRenewingToken.func1()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:773 +0x1b0

Previous read at 0x00c0003042e8 by goroutine 51:
  xxx/vendor/github.com/gopcua/opcua/uasc.(*SecureChannel).signAndEncrypt()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel_crypto.go:35 +0x1db
  xxx/vendor/github.com/gopcua/opcua/uasc.(*SecureChannel).sendAsyncWithTimeout()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:210 +0x20a
  xxx/vendor/github.com/gopcua/opcua/uasc.(*SecureChannel).SendRequestWithTimeout()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:161 +0xa2
  xxx/vendor/github.com/gopcua/opcua.(*Client).sendWithTimeout()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:493 +0xf5
  xxx/vendor/github.com/gopcua/opcua.(*Subscription).publish()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/subscription.go:143 +0x248
  xxx/vendor/github.com/gopcua/opcua.(*Subscription).Run()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/subscription.go:174 +0xc6

Goroutine 28 (running) created at:
  xxx/vendor/github.com/gopcua/opcua.(*Client).scheduleRenewingToken()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:766 +0xf3
  xxx/vendor/github.com/gopcua/opcua.(*Client).openSecureChannel()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:199 +0x120
  xxx/vendor/github.com/gopcua/opcua.(*Client).Dial()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:189 +0x3b0
  xxx/vendor/github.com/gopcua/opcua.(*Client).Connect()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/client.go:146 +0xb5
  xxx/drivers/opcua.(*opcuaClient).Init()
      ${GOPATH}/xxx/drivers/opcua/opcua.go:754 +0x16c
  xxx/handler/device.(*device).Run()
      ${GOPATH}/xxx/handler/device/device.go:510 +0x862

Goroutine 51 (running) created at:
  xxx/vendor/github.com/gopcua/opcua/monitor.(*NodeMonitor).Subscribe()
      ${GOPATH}/xxx/vendor/github.com/gopcua/opcua/monitor/subscription.go:131 +0x17f
  xxx/drivers/opcua.(*opcuaClient).updateSubs()
      ${GOPATH}/xxx/drivers/opcua/opcua.go:688 +0x5e9
  xxx/drivers/opcua.(*opcuaClient).Init()
      ${GOPATH}/xxx/drivers/opcua/opcua.go:770 +0x49f
  xxx/handler/device.(*device).Run()
      ${GOPATH}/xxx/handler/device/device.go:510 +0x862
```

### LINKED ISSUE #460: Data race on security channel timeout
One more data race when when adding option opcua.Lifetime(someDuration)  when it is time to renew. Happening with Prosys simulator server, but not with Kepware.

```
==================
WARNING: DATA RACE
Write at 0x00c0004dc180 by goroutine 47:
  github.com/gopcua/opcua/uasc.(*SecureChannel).reset()
      xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:174 +0x25c
  github.com/gopcua/opcua/uasc.(*SecureChannel).Close.func1()
      xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:839 +0x5e
  github.com/gopcua/opcua/uasc.(*SecureChannel).Close()
      xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:847 +0x2d4
  github.com/gopcua/opcua.(*Client).monitor()
      xxx/vendor/github.com/gopcua/opcua/client.go:323 +0x1364

Previous read at 0x00c0004dc180 by goroutine 48:
  github.com/gopcua/opcua/uasc.(*SecureChannel).popHandler()
      xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:732 +0xcc
  github.com/gopcua/opcua/uasc.(*SecureChannel).sendRequestWithTimeout()
      xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:712 +0x4e5
  github.com/gopcua/opcua/uasc.(*SecureChannel).SendRequestWithTimeout()
      xxx/vendor/github.com/gopcua/opcua/uasc/secure_channel.go:760 +0x135
  github.com/gopcua/opcua.(*Client).sendWithTimeout()
      xxx/vendor/github.com/gopcua/opcua/client.go:764 +0xf5
  github.com/gopcua/opcua.(*Client).sendPublishRequest()
      xxx/vendor/github.com/gopcua/opcua/client_sub.go:512 +0x316
  github.com/gopcua/opcua.(*Client).publish()
      xxx/vendor/github.com/gopcua/opcua/client_sub.go:373 +0x18b
  github.com/gopcua/opcua.(*Client).monitorSubscriptions()
      xxx/vendor/github.com/gopcua/opcua/client_sub.go:355 +0x2c9

Goroutine 47 (running) created at:
  github.com/gopcua/opcua.(*Client).Connect.func1()
      xxx/vendor/github.com/gopcua/opcua/client.go:213 +0x7a
  sync.(*Once).doSlow()
      /Users/xxx/sdk/go1.14.15/src/sync/once.go:66 +0x103
  sync.(*Once).Do()
      /Users/xxx/sdk/go1.14.15/src/sync/once.go:57 +0x68
  github.com/gopcua/opcua.(*Client).Connect()
      xxx/vendor/github.com/gopcua/opcua/client.go:212 +0x27c
  
Goroutine 48 (running) created at:
  github.com/gopcua/opcua.(*Client).Connect.func1()
      xxx/vendor/github.com/gopcua/opcua/client.go:214 +0xb0
  sync.(*Once).doSlow()
      /Users/xxx/sdk/go1.14.15/src/sync/once.go:66 +0x103
  sync.(*Once).Do()
      /Users/xxx/sdk/go1.14.15/src/sync/once.go:57 +0x68
  github.com/gopcua/opcua.(*Client).Connect()
      xxx/vendor/github.com/gopcua/opcua/client.go:212 +0x27c
==================

```

### PR DESCRIPTION
**Pull request by kung-foo**
Enable race detection in tests. Note, this does not _fix_ any of the race conditions.

### CODE REVIEW

**Comment by kung-foo** [comment]
@magiconair should we merge this _knowing_ it will block future PRs until we address the races? I'm not sure how much time I have to track down each race.

**Comment by magiconair** [comment]
How many are there now?

**Comment by magiconair** [comment]
Let's do this right. I'm focusing on this now.

**Comment by magiconair** [comment]
I'll revert this one and re-open the PR. The secure channel implementation needs some serious work.

**Comment by magiconair** [comment]
I've pushed a change to the `Makefile` to run `make test-race` so that we can run the tests with the race detector to fix the issues. Once they're all fixed then we enable tests with the race detector by default. Should have done this sooner.

**Pull request merged**
