### PR TITLE
Update latest code

### PR DESCRIPTION
**Pull request by liuxgo**

### CODE REVIEW

**Comment by magiconair** [comment]
Hi, are these workarounds to issues that you've found?

**Comment by liuxgo** [comment]
Sorry, my bad. I foked before, wanna update the latest code to my forked code. I created a wrong PR.

**Comment by magiconair** [comment]
No problem. I figured that. Please let us know when you've found some issue.

**Comment by liuxgo** [comment]
image

Mybe there is an issue? When Server(PLC) define a custom extension object，it browse the node failed.

**Comment by magiconair** [comment]
It is an unknown extension object I assume. One that you did not register, correct?

**Comment by liuxgo** [comment]
Yes, Server gives an unknown extension object, I did not register.

**Comment by magiconair** [comment]
Yeah, question is whether we should skip or error. Maybe we need to make this configurable.

**Pull request closed without merging**
