### PR TITLE
fix decode NodeID

### PR DESCRIPTION
**Pull request by huskar-t**
When I use `prosys OPC UA Simulation Server` as server, I have the same problem as #550, I borrowed from [python-opcua](https://github.com/FreeOpcUa/python-opcua/blob/master/opcua/ua/ua_binary.py#L333-L361) and fix the Decode method of NodeID, which seems to solve my problem.

### CODE REVIEW

**Comment by huskar-t** [comment]
@kung-foo @magiconair Please review, I really need this fix

**Comment by magiconair** [comment]
Sure. Can you please remove the `_ =` since we don't do that. Can you also look up the relevant part of the spec and add a URL to the code.

**Comment by magiconair** [comment]
Also, please add some tests. No merge without. Thank you.

**Comment by huskar-t** [comment]
> Sure. Can you please remove the `_ =` since we don't do that. Can you also look up the relevant part of the spec and add a URL to the code.

I can't find the client protocol specification on the web, can you give me some specifications or websites that you use?

**Comment by magiconair** [comment]
@huskar-t You should find the `NodeID` specification somewhere in here: This is a link to the `ExpandedNodeId` but you should find the TCP/IP binary representation model somewhere in here as well.

https://reference.opcfoundation.org/v104/Core/docs/Part4/7.11/

**Comment by huskar-t** [comment]
@magiconair Thank you very much, but after reading the code it seems that I made a mistake, I will solve this problem as soon as possible. Maybe close this pr first and create a new one after I solve it

**Comment by magiconair** [comment]
Sounds good.

**Pull request closed without merging**
