### PR TITLE
Solves failing tests on windows

### LINKED ISSUE #228: config_test.go fails on Windows
`config_test.go` hardcodes filenames like "/tmp/gopcua-test-cert.der" instead of using `ioutil.TestFile()` or `ioutil.TestDir()`. Naturally, the test fails on Windows.

### PR DESCRIPTION
**Pull request by kmpm**
Fixes #228

### CODE REVIEW

**Review by dwhutchison — COMMENTED** [review]
Thanks for the PR!

I've tested this on my Windows machine and it works well. 
Please see some minor comments below.

**Comment by magiconair** [comment]
I think this is too complex. This should do the trick. Can someone test this on Windows:

```patch
diff --git a/config_test.go b/config_test.go
index f4ea0fb..5d20e6b 100644
--- a/config_test.go
+++ b/config_test.go
@@ -6,6 +6,7 @@ import (
 	"encoding/pem"
 	"io/ioutil"
 	"os"
+	"path/filepath"
 	"testing"
 	"time"
 
@@ -16,13 +17,6 @@ import (
 	"github.com/pascaldekloe/goe/verify"
 )
 
-const (
-	certDERFile = "/tmp/gopcua-test-cert.der"
-	certPEMFile = "/tmp/gopcua-test-cert.pem"
-	keyDERFile  = "/tmp/gopcua-test-key.der"
-	keyPEMFile  = "/tmp/gopcua-test-key.pem"
-)
-
 // test certificate generated with
 // go run ~/sdk/gotip/src/crypto/tls/generate_cert.go -rsa-bits 1024 -host localhost
 // expires Jun  5 20:10:13 2020 GMT
@@ -129,22 +123,31 @@ func x509Cert(c, k []byte) tls.Certificate {
 }
 
 func TestOptions(t *testing.T) {
+	d, err := ioutil.TempDir("", "gopcua")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer os.RemoveAll(d)
+
+	var (
+		certDERFile = filepath.Join(d, "cert.der")
+		certPEMFile = filepath.Join(d, "cert.pem")
+		keyDERFile  = filepath.Join(d, "key.der")
+		keyPEMFile  = filepath.Join(d, "key.pem")
+	)
+
 	if err := ioutil.WriteFile(certDERFile, certDER, 0644); err != nil {
 		t.Fatal(err)
 	}
-	defer os.Remove(certDERFile)
 	if err := ioutil.WriteFile(certPEMFile, certPEM, 0644); err != nil {
 		t.Fatal(err)
 	}
-	defer os.Remove(certPEMFile)
 	if err := ioutil.WriteFile(keyDERFile, keyDER, 0644); err != nil {
 		t.Fatal(err)
 	}
-	defer os.Remove(keyDERFile)
 	if err := ioutil.WriteFile(keyPEMFile, keyPEM, 0644); err != nil {
 		t.Fatal(err)
 	}
-	defer os.Remove(keyPEMFile)
 
 	tests := []struct {
 		name string
```

**Comment by kmpm** [comment]
@magiconair have a simpler solution that works on windows so I changed my pull-request and force-pushed.

**Comment by magiconair** [comment]
Thank you.

**Pull request merged**
