### PR TITLE
Add GoDoc comments about Option handling

### PR DESCRIPTION
**Pull request by wmnsk**
Just added a few lines of godoc comments for handling Option in NewClient.

### CODE REVIEW

**Comment by magiconair** [comment]
Will that still be correct once #182 is merged?

**Comment by wmnsk** [comment]
I've just corrected. Could you check again?

**Comment by magiconair** [comment]
There are a couple of typos. If you push the branch to this repo then I can fix them.

**Comment by magiconair** [comment]
@wmnsk since you're one of the admins you don't have to fork to your own repo to send a PR.

**Comment by wmnsk** [comment]
OK, I’ll do that later.

**Comment by wmnsk** [comment]
Re-opened in #193, as just pushing the branch directly to `gopcua` did not overwrite this PR.

**Pull request closed without merging**
