### PR TITLE
test with go1.12 on circleci

### PR DESCRIPTION
**Pull request by magiconair**
circle-ci does not have a go1.12 container yet.

### CODE REVIEW

**Comment by wmnsk** [comment]
I’d like to keep this package follow the policy that golang itself follows officially. 
https://golang.org/doc/devel/release.html#policy

So, at the time CCI become compatible with Go 1.12, the task for 1.10 should be removed.

**Comment by magiconair** [comment]
Dropped support for go1.10

**Comment by wmnsk** [comment]
Thanks!

For GO111MODULES, `on` should be quoted not to be interpreted as true by yaml.

```yaml
        environment:
          GO111MODULE: "ON"
```

https://circleci.com/blog/go-v1.11-modules-and-circleci/

**Comment by magiconair** [comment]
Was just looking at that. :)

**Comment by wmnsk** [comment]
Reran CCI.
Now the container for 1.12 is available but it seems we’re facing another problem...

**Comment by magiconair** [comment]
I've dropped the linter since you are using the GolangCI bot. Also dropped the working directory since checking out to the home dir will force the new module behavior.

**Comment by wmnsk** [comment]
Looking good, thank you!

**Pull request merged**
